### ISSUE TITLE
Structurizr Lite destroys work on workspace

### ISSUE THREAD

**Issue by ss-traviswilliams** [structurizr/lite#5]
I don't know how reproducible this is, but here's a walkthrough of what I did, along with a gist of the error log 

1. Build context view
2. Auto layout with button
3. Work through layout, changing styles, tag names, and other normal behavior
4. Export to png
5. Left for lunch hour (expecting this is the problem based on logs)
6. Came back, changed another tag
7. Refresh layout, get a completely baseline layout, no recovery possible

This has happened several times. We're using source control for `workspace.dsl` and `workspace.json`. I cannot use the undo layout changes button, as it seems to have also destroyed all history in the process. 

attached error log
https://gist.github.com/ss-traviswilliams/785a90fdfd03c6195a8f746901348c72

**Comment by simonbrowndotje** [comment]
I'm not sure what the problem is, but perhaps some tips may help:

- Structurizr Lite is only designed to be a single user application.
- Ensure that only single instance of Lite is started against the same DSL folder (the logs suggest some file locking issues).
- From a quick look at the cloud service workspace history, it seems multiple Structurizr Lite instances have modified the same workspace, so you may want to use the workspace locking feature -> https://structurizr.com/share/76352/documentation/Structurizr%20Lite#workspace-locking

Any old version of the `workspace.json` file can be restored to the cloud service (https://structurizr.com/help/workspace-export-and-import ... use `-merge false` with the CLI to force the layout in the JSON file to be used), so that's your best option when layout is lost.

Finally, you have some strange messages in the log file ... `PageNotFound - No mapping for GET /struts2-showcase/struts/tooltip.gif`, `Invalid character found in the request target [/js/?${jndi:dns://MDEDiscovery6877259e9aSeenInTheWildGet-8080}`, etc. Are you running Lite on the public Internet?
